### ISSUE TITLE
Fix pip upgrade in the CircleCI build script

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-networkx#197]
See https://github.com/dwavesystems/dwave-networkx/pull/196#issuecomment-840029418.

**Comment by JoelPasvolsky** [comment]
Did you mean to open a separate PR for this or is it okay that I just fix it in https://github.com/dwavesystems/dwave-networkx/pull/196

**Comment by randomir** [comment]
Just fix it. :laughing:

**Comment by JoelPasvolsky** [comment]
Fixed in https://github.com/dwavesystems/dwave-networkx/pull/196 👍
